
# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: philips-software/docker-ci-scripts@v2.2.1
        with:
          dockerfile: 'dockerfile'
          image-name: 'wol-api'
          tags: 'latest'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
          DOCKER_ORGANIZATION: therauch1